repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        args: ["--profile", "black", "."]
        files: \.py$
      - id: black
        name: black
        entry: black
        language: system
        args: ["."]
        files: \.py$
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        args: ["--namespace-packages", "--explicit-package-bases"]
        files: \.py$
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        args: ["--maxfail=1", "--disable-warnings", "--cov=src/iplens", "--cov-fail-under=75", "tests/"]
        files: ^tests/.*\.py$
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        args: ["-q", "-r", "src/iplens", "-s", "B608", "-s", "B104"]
        files: ^src/iplens/.*\.py$



